### ISSUE TITLE
Corner case and Bugs in Join Teams

### ISSUE THREAD

**Issue by nathaishik** [nathaishik/igem-2024-website#9]
Users who have not been assigned any position yet get a template error page when trying to join teams.
![IMG-20240618-WA0000](https://github.com/nathaishik/igem-2024-website/assets/135934365/2c7aa128-28d2-4ac6-b2df-363d8efc8d39)

Also, all members are able to modify leaders and memberes of all other teams.

**Comment by Kalpit-prabhat** [comment]
giving new users a default initial position of 1 should solve both issues

**Comment by nathaishik** [comment]
Issue resolved in Commit e225eb235289c7b355f2fedadcaa2c1a7eee5b0e
